### ISSUE TITLE
Why do you need to have user.is_customer field when you can have Customer table inherits from User table

### ISSUE THREAD

**Issue by dodyg** [silverkeytech/house-care#2]
![image](https://github.com/silverkeytech/house-care/assets/1761249/3ec4bf38-e0fd-41c8-9506-59c0c8fa9275)

Just like you do in inheriting `MaintenancePersonnel`?

**Comment by nourhanhelmy1** [comment]
is_customer was later changed to is_logged in it is supposed to indicate whether the user has an account or just logged in as a guest. We will use a different approach as agreed in the meeting to add user id (uuid) that can be nullable if the user is not logged in instead of using the is_loggedin approach. To be done.

**Comment by nourhanhelmy1** [comment]
Done.
